#MAKEFILE FOR OS PROJECT
#Authored by Joseph Walewski & Clayton Carter
#TO RUN, type "make" while in the SRC directory

.PHONY: default

default: clean
	g++ ./*.cpp ./*.h -Wall && ./a.exe

clean:
	rm -f ./*.out ./*.exe